/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyecto_basedatos.Cajero;

/**
 *
 * @author Wilson Pinos
 */
public class Consulta_cajero extends javax.swing.JFrame {

    /**
     * Creates new form Consulta_bus
     */
    private Modificar_cajero modificar;
    private String id = "";
    private String cedula = "";
    private String nombre = "";
    private String apellido = "";
    private String correo = "";
    private String celular = "";
    private String nivel_est = "";
    private String turno = "";
    private int edad = 1;
    private Date fecha_nac = null;
    private Date fec_contrat = null;

    public Consulta_cajero() {
        initComponents();
        BuscarCajero();
        tblcajero.addMouseListener(new MouseAdapter() {
            DefaultTableModel model = new DefaultTableModel();

            public void mouseClicked(MouseEvent e) {
                int i = tblcajero.getSelectedRow();
                id = tblcajero.getValueAt(i, 0).toString();
                cedula = tblcajero.getValueAt(i, 1).toString();
                nombre = tblcajero.getValueAt(i, 3).toString();
                apellido = tblcajero.getValueAt(i, 4).toString();
                correo = tblcajero.getValueAt(i, 5).toString();
                celular = tblcajero.getValueAt(i, 6).toString();
                nivel_est = tblcajero.getValueAt(i, 7).toString();
                turno = tblcajero.getValueAt(i, 8).toString();
                edad = (int) tblcajero.getValueAt(i, 9);
                fecha_nac = (Date) tblcajero.getValueAt(i, 10);
                fec_contrat = (Date) tblcajero.getValueAt(i, 11);
            }

        });
    }

    public void setModificar_cajero(Modificar_cajero modificar) {
        this.modificar = modificar;
    }

    public void BuscarCajero() {

        ObjectContainer base = Db4o.openFile(proyecto_basedatos.BDdireccion);
        Cajero caje = new Cajero(null, null, null, null, null, null, null, null, 0, null, null);
        ObjectSet resultado = base.get(caje);
        String matriz[][] = new String[resultado.size()][11];
        int i = 0;
        while (resultado.hasNext()) {
            Cajero tablacajero = (Cajero) resultado.next();
            matriz[i][0] = tablacajero.getId_cajero();
            matriz[i][1] = tablacajero.getCedula();
            matriz[i][2] = tablacajero.getNombre();
            matriz[i][3] = tablacajero.getApellido();
            matriz[i][4] = tablacajero.getCorreo();
            matriz[i][5] = tablacajero.getCelular();
            matriz[i][6] = tablacajero.getNivel_estudio();
            matriz[i][7] = tablacajero.getTurno();
            //de int a string para la matriz de strings
            int auxedad = tablacajero.getEdad();
            String edad = Integer.toString(auxedad);
            matriz[i][8] = edad;
            //de date a string
            Date auxnacim = tablacajero.getNacimiento();
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
            String nacim = formatoFecha.format(auxnacim);
            matriz[i][9] = nacim;
            Date auxfec_cont = tablacajero.getFec_contratacion();
            String fec_cont = formatoFecha.format(auxfec_cont);
            matriz[i][10] = fec_cont;

            i++;

        }
        tblcajero.setModel(new javax.swing.table.DefaultTableModel(matriz, new String[]{"ID", "Cedula", "Nombre", "Apellido", "Correo", "Celular", "Nivel de estudio", "Turno", "Edad", "Fecha de nacimiento", "Fecha de contratacion"}));
        CerrarBD(base);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcajero = new javax.swing.JTable();
        btnbuscar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        btnregresar = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo.setText("CONSULTA DE CAJERO");

        tblcajero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblcajero);

        btnbuscar.setText("BUSCAR");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnregresar.setText("REGRESAR");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        btnborrar.setText("BORRAR");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        btnmodificar.setText("MODIFICAR");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addComponent(btnbuscar)
                                .addGap(18, 18, 18)
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(btnregresar)
                                .addGap(51, 51, 51)
                                .addComponent(btnborrar)
                                .addGap(37, 37, 37)
                                .addComponent(btnmodificar)))
                        .addGap(0, 213, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbuscar)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregresar)
                    .addComponent(btnborrar)
                    .addComponent(btnmodificar))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        dispose();
        Ingreso_cajero ing = new Ingreso_cajero();
        ing.setVisible(true);
    }//GEN-LAST:event_btnregresarActionPerformed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        ObjectContainer base = Db4o.openFile(proyecto_basedatos.BDdireccion);
        Cajero Bcajero = new Cajero(id, null, null, null, null, null, null, null, 0, null, null);
        ObjectSet resultado = base.get(Bcajero);
        while (resultado.hasNext()) {
            Cajero Bcaje = (Cajero) resultado.next();
            if (JOptionPane.showConfirmDialog(rootPane, "¿Deseas continuar?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                if (id.equals(Bcaje.getId_cajero())) {
                    base.delete(Bcaje);

                }
            }
        }
        CerrarBD(base);
        BuscarCajero();
    }//GEN-LAST:event_btnborrarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        ObjectContainer base = Db4o.openFile(proyecto_basedatos.BDdireccion);
        Cajero caje = new Cajero(null, null, null, null, null, null, null, null, 0, null, null);
        ObjectSet resultado = base.get(caje);
        String matriz[][] = new String[resultado.size()][2];
        int i = 0;
        while (resultado.hasNext()) {
            Cajero tablacajero = (Cajero) resultado.next();
            if (tablacajero.getCedula().toLowerCase().contains(txtbuscar.getText().toLowerCase())) {
                matriz[i][0] = tablacajero.getId_cajero();
                matriz[i][1] = tablacajero.getCedula();
                matriz[i][2] = tablacajero.getNombre();
                matriz[i][3] = tablacajero.getApellido();
                matriz[i][4] = tablacajero.getCorreo();
                matriz[i][5] = tablacajero.getCelular();
                matriz[i][6] = tablacajero.getNivel_estudio();
                matriz[i][7] = tablacajero.getTurno();
                //de int a string para la matriz de strings
                int auxedad = tablacajero.getEdad();
                String edad = Integer.toString(auxedad);
                matriz[i][8] = edad;
                //de date a string
                Date auxnacim = tablacajero.getNacimiento();
                SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
                String nacim = formatoFecha.format(auxnacim);
                matriz[i][9] = nacim;
                Date auxfec_cont = tablacajero.getFec_contratacion();
                String fec_cont = formatoFecha.format(auxfec_cont);
                matriz[i][10] = fec_cont;
                i++;
            }
        }
        tblcajero.setModel(new javax.swing.table.DefaultTableModel(matriz, new String[]{"ID", "Cedula", "Nombre", "Apellido", "Correo", "Celular", "Nivel de estudio", "Turno", "Edad", "Fecha de nacimiento", "Fecha de contratacion"}));
        CerrarBD(base);
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        if(!id.isBlank()){
        dispose();
        Modificar_cajero modi = new Modificar_cajero();
        modi.recibirCodigo(id,cedula,nombre,apellido,correo,celular,nivel_est,turno,edad,fecha_nac,fec_contrat); // Envía el valor 
        modi.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Para modificar, primero selecciona un registro");
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta_cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta_cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta_cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta_cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta_cajero().setVisible(true);
            }
        });
    }

    public static void CerrarBD(ObjectContainer base) {
        base.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnregresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTable tblcajero;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
