package interfaces;

import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import com.db4o.query.Query;
import static interfaces.proyecto_basedatos.BDdireccion;
import proyecto_basedatos.Bus;
import proyecto_basedatos.Conductor;
import proyecto_basedatos.Historial_asignacion;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author mauri
 */
public class historial extends javax.swing.JFrame {

    /**
     * Creates new form historial
     */
    public historial() {
        initComponents();
    }

    public void RecuperarDato() {
        ObjectContainer db = null;

        try {
            // Abrir la base de datos (puedes cambiar el nombre del archivo.db4o según tus necesidades)
            db = Db4o.openFile(BDdireccion);

            Conductor con = new Conductor();
            con.setId_conductor(id_conductor.getText());

            Bus bus1 = new Bus();
            bus1.setMatricula(cbxbus.getSelectedItem().toString());

            Historial_asignacion his = new Historial_asignacion();
            his.setCondu(con);
            his.setBu(bus1);

            // Guardar los objetos Padre e Hijo en la base de datos
            db.store(bus1);
            db.store(con);
            db.store(his);

            Query query = db.query();
            query.constrain(Conductor.class);
            ObjectSet<Conductor> result = query.execute();

            StringBuilder id_conductor = new StringBuilder();
            while (result.hasNext()) {
                Conductor conductorRecuperado = result.next();
                id_conductor.append("Conductor: ").append(conductorRecuperado.getId_conductor()).append("\n");
                id_conductor.append("Asignaciones:\n");

                Query queryAsignaciones = db.query();
                queryAsignaciones.constrain(Historial_asignacion.class);
                queryAsignaciones.descend("condu").constrain(conductorRecuperado).identity();
                ObjectSet<Historial_asignacion> asignaciones = queryAsignaciones.execute();

                while (asignaciones.hasNext()) {
                    Historial_asignacion historia = asignaciones.next();
                    id_conductor.append("- Bus: ").append(historia.getBu().getMatricula()).append("\n");
                }

                id_conductor.append("-----------------------\n");
            }

           // txtResultado.setText(resultadoText.toString());

            db.commit();
        } finally {
            if (db != null) {
                db.close();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxbus = new javax.swing.JComboBox<>();
        id_conductor = new javax.swing.JTextField();
        txthistorial = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        dcfechafin = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "-----------------------------------HISTORIAL---------------------------", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("--------------------------------------------------------------------------------");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 640, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("FECHA DE ASIGNACION:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 240, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("ID DEL HISTORIAL:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 190, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("BUS ASIGNADO :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 190, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("ID DEL CONDUCTOR:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 190, 30));

        cbxbus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 200, 20));
        jPanel1.add(id_conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 200, -1));
        jPanel1.add(txthistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 200, -1));

        jTextField4.setText("jTextField1");
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 200, -1));
        jPanel1.add(dcfechafin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new historial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxbus;
    private com.toedter.calendar.JDateChooser dcfechafin;
    private javax.swing.JTextField id_conductor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txthistorial;
    // End of variables declaration//GEN-END:variables
}
